[package]
name = "monto-parenlang"
version = "0.1.0"
authors = ["Nathaniel Ringo <remexre@gmail.com>"]

[dependencies]
either = "^1.1.0"
itertools = "^0.6.0"
monto = { path = ".." }
serde_json = "^1.0.2"
tokio-core = "^0.1.8"
void = "^1.0.2"
