language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
matrix:
  fast_finish: true

script:
- cargo build --all
- cargo test --all

before_deploy:
- cargo build --release --all
- mkdir staging
- TODO
deploy:
  provider: releases
  file: monto-rs-$(TARGET)-$(TRAVIS_TAG).tar.gz
  on:
    tags: true
    condition: "$(TRAVIS_RUST_VERSION) = stable"
  description: "$(TRAVIS_TAG) release"
  api_key:
    secure: vvbNSmMFScrBRNkDhTSwLkqV0AcRPb2QJHLpSU7zyrlCPJBfjQrmqeEP9GjW2tqBPZiUIQmKlJT4HNDClZGLht1roj3gxhxz/aSOvjUKZpTF5myf11I5qUU8P7G01mbEIP62qft7Hj2xGx6uyfX5pHOmw+h0Pb3bXYkmtrjATAIgPq5wkNlxE+OhR6g7/upF7CRqzNudfp93tSWHfh98n6Ic7ooysqxgWvNHZruo3De0zrlpcbI++x3qJ5eUtpbKSuw/faBQos0rqwO4NII/RCuNBk+UbmA5BZytb30sO40VHaDFEOgXA2K5h9EhUoJaPdsWEfL2euZmVFF+fxrV6c63jr6MiZcS9PgjtcjO9WEwDLM8wbqAjBXppqLUI0GE/4H+Nilv/HMNvlCexNgj5c5050jWTkJNtRS7wg9XrK/Lr9czv0EiBwCm3cIbpExsjJQNL3Oe39o3ifmwTWaRMR6LvXbsVvEwDHoDjUw0xN8FwHpBhXrsVGCDgxiPp/I0/nKtnwFp/0lvROBUvB6bhSVAzEAHTJ8e/thuwJs4nCQ3w+HNvZzteNsVRUjCfmworr8da4+muVMvVHQBGFzq3PI/DmJjjX1jez1xA/EytGJvflUnQrQ001vzEkKiS04AGMkUjf0VF1tW+wIHLqQXWr/ljzTEcE2oWjeuuERaIj0=
  skip_cleanup: true

notifications:
  slack:
    secure: szbWFA9tRFtIzl+XavdU8C04w1nJXQLTuWm3VgPR284QRaDzJDSFwKDcFG+rH6YYKpzqSpnIbonNeNVKPMJ3coyyJrBiaFB2e7gvRia3ecowkfQKcfTufutU8fNvVzK6MRy/spUuQeXTUEQ6hhZfUhkBwFViMBHAYdRlW5W6TqFcVSKGMKJcDYJ00ts73FCdvuYpZcRMh+pDrsF70ZB+jFsI73/g2spFGf3sNMA2CK1shIWJVdsS6IfEslN4RQtyXFyR/iDkhptbKbphSJtpEVP6ycbig1ODmXOVIOGI9k9rOVnE+9orzq6/f0sbxzuPLOd15E4wk5a6dClWyNQ1z3xVPLwf+QMDMWyrAC4Ke8QAzDuIKLnCRQ32oOcyvgrZ5UZ/w7IJRWURcJ+nfA7MKyKMODxexN/UyOXx0qUkSZ8j3d8GJuOFTg0t7C6gGn06EEyCAMUue/rXxZ1WbuYNkIQYvrb859edXPbQEX2DxsFBmHCzaBTdTjShJosNWPuAQmtyQr+cZPHl+i9XoZ7lJRn0Q3Sg6e6QRDBF2LFCMS4bvF+O9HCClO86mGIdleVpw9HhryYa9J38tsjkA+HakWF0ZIHtBqFPLJmNpPTvdXKNtszcWAIfxUx4Vy1uMi+KNn0xLDrgkMWJJzwh/r+mjrFhA8FNGLn9H1cvGUfRPoU=
