environment:
  matrix:
  - TARGET: i686-pc-windows-gnu
    RUST_VERSION: stable
  - TARGET: i686-pc-windows-gnu
    RUST_VERSION: beta
  - TARGET: i686-pc-windows-gnu
    RUST_VERSION: nightly
  - TARGET: x86_64-pc-windows-gnu
    RUST_VERSION: stable
  - TARGET: x86_64-pc-windows-gnu
    RUST_VERSION: beta
  - TARGET: x86_64-pc-windows-gnu
    RUST_VERSION: nightly
  - TARGET: i686-pc-windows-nightly
    RUST_VERSION: stable
  - TARGET: i686-pc-windows-nightly
    RUST_VERSION: beta
  - TARGET: i686-pc-windows-nightly
    RUST_VERSION: nightly
  - TARGET: x86_64-pc-windows-nightly
    RUST_VERSION: stable
  - TARGET: x86_64-pc-windows-nightly
    RUST_VERSION: beta
  - TARGET: x86_64-pc-windows-nightly
    RUST_VERSION: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

build_script:
  - cargo build --all
  - cargo build --all --release

test_script:
  - cargo test --all

matrix:
  fast_finish: true
