branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
environment:
  matrix:
  - TARGET: i686-pc-windows-gnu
    RUST_VERSION: stable
  - TARGET: i686-pc-windows-gnu
    RUST_VERSION: beta
  - TARGET: i686-pc-windows-gnu
    RUST_VERSION: nightly
  - TARGET: x86_64-pc-windows-gnu
    RUST_VERSION: stable
  - TARGET: x86_64-pc-windows-gnu
    RUST_VERSION: beta
  - TARGET: x86_64-pc-windows-gnu
    RUST_VERSION: nightly
  - TARGET: i686-pc-windows-msvc
    RUST_VERSION: stable
  - TARGET: i686-pc-windows-msvc
    RUST_VERSION: beta
  - TARGET: i686-pc-windows-msvc
    RUST_VERSION: nightly
  - TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: stable
  - TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: beta
  - TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: nightly
matrix:
  fast_finish: true

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

build_script:
  - cargo build

test_script:
  - cargo test

before_deploy:
  - cargo build --release
  - mkdir staging
  - TODO
deploy:
  - provider: GitHub
    artifact: monto-rs-$(TARGET)-$(APPVEYOR_REPO_TAG_NAME).zip
    on:
      appveyor_repo_tag: true
    description: $(APPVEYOR_REPO_TAG_NAME) release
    auth_token:
      secure: SockYqLSroVMPUR6nq6Eom/pZ5t04SmO/zP4S0yyo2WdthcXVDUmv+4ZYQDuYo9H
