[badges.appveyor]
repository = "remexre/monto-rs"

[badges.travis-ci]
repository = "melt-umn/monto-rs"

[workspace]
members = [
	"broker",
	"client",
	"common",
	"service",
	"services/monto-cpp",
	"services/monto-example-services",
	"services/monto-loctrans",
]
