[package]
authors = ["Nathaniel Ringo <remexre@gmail.com>"]
license = "Apache-2.0/MIT"
name = "monto-c"
version = "0.1.0"

[dependencies]
monto = { path = "../.." }

[lib]
crate-type = ["cdylib", "staticlib"]
name = "monto"
