[package]
authors = ["Nathaniel Ringo <remexre@gmail.com>"]
name = "monto3-c"
version = "0.1.0"

[dependencies]
monto3 = { path = "../.." }

[lib]
crate-type = ["cdylib", "staticlib"]
name = "monto3"
