[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
name = "monto3-common"
version = "0.2.0"

[dependencies]
either = "1.4.0"
futures = "0.1.17"
hyper = "0.11.7"
lazy_static = "1.0.0"
regex = "0.2.3"
semver = "0.9.0"
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.6"
